## Ответы к Notebook 01_Intro_Numpy

In [ ]:
# Выполни прежде чем проходить Notebook
from google.colab import drive
import os
drive.mount ('/content/gdrive', force_remount=True)

%run /content/gdrive/MyDrive/02_NumPy_and_Pandas/0_package_installation.ipynb
# Перезагрузка ядра
os.kill(os.getpid(), 9)

Mounted at /content/gdrive
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 38.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.8/341.8 kB 33.9 MB/s eta 0:00:00
  Attempting uninstall: pandas
    Found existing installation: pandas 1.5.3
    Uninstalling pandas-1.5.3:
      Successfully uninstalled pandas-1.5.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==1.5.3, but you have pandas 2.0.3 which is incompatible.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 28.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.3/98.3 kB 8.7 MB/s eta 0:00:00
  Attempting uninstall: pyparsing
    Found existing installation: pyparsing 3.1.1
    Uninstalling pyparsing-3.1.1:
      Successfully uninstalled pyparsing-3.1.1
  Attempting uninstall: matplotlib
    Found existing installation:

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 44.7 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.23.5
    Uninstalling numpy-1.23.5:
      Successfully uninstalled numpy-1.23.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.25.2 which is incompatible.
tensorflow 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.25.2 which is incompatible.


In [ ]:
# Задача 3.1.2
import numpy as np
data_ndarray = np.array([10,20,30])
print(data_ndarray)

In [ ]:
# Задача 3.1.3
taxi = np.array(converted_taxi_list)

In [ ]:
# Задача 3.1.5
row_0 = taxi[0]
rows_391_to_500 = taxi[391:500]
row_21_column = taxi[21,5]

In [ ]:
# Задача 3.1.6
cols_1 = [1,4,7]
columns_1_4_7 = taxi[:,cols_1]
row_99_columns_5_to_8 = taxi[99,5:8]
rows_100_to_200_column_14 = taxi[100:200,14]

In [ ]:
# Задача 3.1.9
trip_distance = taxi[:,7]
trip_distance_miles = taxi[:,7]
trip_length_seconds = taxi[:,8]

trip_length_hours = trip_length_seconds / 3600
trip_mph = trip_distance_miles / trip_length_hours

distance_max = np.max(trip_distance)
distance_mean = np.mean(trip_distance)
print(distance_max,distance_mean)

In [ ]:
# Задача 3.1.10
fare_components = taxi[:5,[9,10,11,12]]
taxi_first_five = taxi[:5]

fare_sums = np.sum(fare_components)
fare_totals = np.sum(taxi_first_five[:,13])
print(fare_sums,fare_totals)

## Ответы к Notebook 02_Numpy_boolean_indexes

In [ ]:
# Задача 3.2.1
february_bool = pickup_month == 2
february = pickup_month[february_bool]
february_rides = february.shape[0]
print(february_rides)

In [ ]:
# Задача 3.2.2
tip_bool = taxi[:,12] > 50
print(tip_bool.sum())
top_tips = taxi[tip_bool,5:13]
print(top_tips.shape)

## Ответы к Notebook 03_Intro_Pandas

In [ ]:
# Задача 3.3.2
f500_type = type(f500)
f500_shape = f500.shape
print(f500_type,f500_shape)

In [ ]:
# Задача 3.3.3
f500_head = f500.head(6)
f500_tail = f500.tail(8)
print(f500_head.shape,f500_tail.shape)

In [ ]:
# Задача 3.3.4
f500.info()

In [ ]:
# Задача 3.3.5
industries = f500['industry']
industries_type = type(industries)
print(industries_type)

In [ ]:
# Задача 3.3.6
countries = f500['country']
revenues_years = f500.loc[:,['revenues','years_on_global_500_list']]
ceo_to_sector = f500.loc[:,'ceo':'sector']

In [ ]:
# Задача 3.3.7
toyota = f500.loc['Toyota Motor']
drink_companies = f500.loc[['Anheuser-Busch InBev','Coca-Cola','Heineken Holding']]
middle_companies = f500.loc['Tata Motors':'Nationwide','rank':'country']

In [ ]:
# Задача 3.3.8
countries = f500['country']
country_counts = countries.value_counts()
country_counts

## Ответы к Notebook 04_Pandas_boolean_indexes

In [ ]:
# Задача 3.4.2
rank_change = f500['rank'] - f500['previous_rank']

In [ ]:
# Задача 3.4.3
rank_change_max = rank_change.max()
rank_change_min = rank_change.min()
print(rank_change_max,rank_change_min)

In [ ]:
# Задача 3.4.4
rank = f500.loc[:,'rank']
rank_desc = rank.describe()
prev_rank = f500.loc[:,'previous_rank']
prev_rank_desc = prev_rank.describe()

In [ ]:
# Задача 3.4.5
zero_previous_rank = f500.loc[f500['previous_rank'] == 0,'previous_rank'].value_counts()

In [ ]:
# Задача 3.4.6
max_f500 = f500.max(axis="index",numeric_only = True)

In [ ]:
# Задача 3.4.7
f500_desc = f500.describe()

In [ ]:
# Задача 3.4.8
f500.loc['Dow Chemical','ceo'] = 'Jim Fitterling'

In [ ]:
# Задача 3.4.9
motor_bool = f500['industry'] == 'Motor Vehicles and Parts'
motor_countries = f500[motor_bool].country

In [ ]:
# Задача 3.4.10
import numpy as np

prev_rank_before = f500['previous_rank']
prev_rank_after = f500.loc[f500['previous_rank'] == 0, 'previous_rank'] = np.nan
prev_rank_before

In [ ]:
# Задача 3.4.11
f500['rank_change'] = f500['rank'] - f500['previous_rank']
rank_change_desc = f500['rank_change'].describe()
rank_change_desc

## Ответы к Notebook 05_Data_Aggregation_merging

In [ ]:
# Задача 5.2.1
filter_c = data['type'] == 'conventional'
filter_c
data_conventional = data.loc[filter_c]
data_conventional

In [ ]:
# Задача 5.2.2
avg_conventional = data_conventional['AveragePrice'].mean()
avg_conventional

In [ ]:
# Задача 5.3.1
by_year = data.groupby(['type', 'year', 'region'])['Large Hass Avocado'].sum()
print(by_year)

In [ ]:
# Задача 5.4.1
data.agg({'Large Bags' : ['mean', percentile_95], 'Small Bags' : ['mean', percentile_95], 'XLarge Bags':['mean',percentile_95]})

In [ ]:
# Задача 5.4.2
_by_type = data.groupby('type')['Total Volume'].count()
_by_type

In [ ]:
# Задача 5.5.1
pd.merge(data_1, data_2, on = 'key', how = 'right')

In [ ]:
# Задача 5.5.2
pd.merge(data_1, data_2, on = 'key', how = 'outer')

## Ответы к Notebook 06_Practice_time

In [ ]:
# Задача 1
import numpy as np
Z = np.arange(11)
Z_1 = Z[(3 < Z) & (Z < 8)]
print(Z_1)

[4 5 6 7]


In [ ]:
# Задача 2
Y = np.zeros(10)
Y[4] = 1
print(Y)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
# Задача 3
Z_1 = np.arange(50)
Z_1 = Z_1[::-1]
print(Z_1)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [ ]:
# Задача 4
Z_4 = np.random.random((10,10))
Zmin, Zmax = Z_4.min(), Z_4.max()
print(Zmin, Zmax)

0.01696881845183984 0.99713765497518


In [ ]:
# Задача 5
import pandas as pd
ser = pd.Series(np.random.normal(10, 5, 25))
np.percentile(ser, q=[0, 25, 50, 75, 100])

array([-4.22601127,  5.96728329,  9.83975276, 11.47130796, 19.5380751 ])

In [ ]:
# Задача 6
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

ser.value_counts()

c    7
d    6
e    5
b    4
f    4
h    2
g    1
a    1
dtype: int64

In [ ]:
# Задача 7
data = {'col_1': [3, 2, 1, np.NaN], 'col_2': ['a', 'b','c', 'd']}
df = pd.DataFrame.from_dict(data)
df.isnull().values.any()

In [ ]:
# Задача 8
avacod_df = pd.read_csv("avocado.csv", index_col='Date')
avacod_df.loc['2018-03-25', ['AveragePrice', 'Total Volume', 'type', 'year', 'region']]

In [ ]:
# Задача 9
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})
out = df.groupby('fruit', as_index=False).agg({'price':'mean', 'rating': 'max'}).rename(columns={'price':'mean_price','rating': 'max_rating'})
print(out)


    fruit  mean_price  max_rating
0   apple    6.666667    0.775386
1  banana   12.666667    0.934426
2  orange    7.666667    0.931254


In [ ]:
# Задача 10
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})
pd.merge(df1, df2, how='inner', left_on=['fruit', 'weight'], right_on=['pazham', 'kilo'], suffixes=['_left', '_right'])


fruit weight  price_left  pazham  kilo  price_right
0   apple   high           9   apple  high            5
1   apple   high           6   apple  high            5
2   apple   high          12   apple  high            5
3  orange    low           3  orange   low           14
4  orange    low           6  orange   low           14
5  orange    low           0  orange   low           14